trigger:
- '*'

variables:
  tag: '$(Build.BuildId)'
  containerRegistry: 'devacr-sc'
  repository: 'dotnet'
  ResourceGroup: 'devops-rg'
pool:
     vmImage: 'windows-latest'
stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: DotNet 
    displayName: DotNet Build and Test   
    steps:
    - task: DotNetCoreCLI@2
      inputs:
        command: 'restore'
        projects: 'Tailspin.SpaceGame.Web/Tailspin.SpaceGame.Web.csproj'
        feedsToUse: 'select'
    - task: DotNetCoreCLI@2
      inputs:
        command: 'build'
        projects: 'Tailspin.SpaceGame.Web/Tailspin.SpaceGame.Web.csproj'
        arguments: '-c Release -o $(Build.SourcesDirectory)/app/build'
        zipAfterPublish: true
    - task: DotNetCoreCLI@2
      inputs:
        command: 'test'
        projects: 'Tailspin.SpaceGame.Web/*.csproj'
    - task: DotNetCoreCLI@2
      inputs:
        command: 'publish'
        publishWebProjects: true
<<<<<<< HEAD
        arguments: '-c Release -o $(Build.SourcesDirectory)/Tailspin.SpaceGame.Web/After/publish'
=======
        arguments: '-c Release -o $(Build.SourcesDirectory)/app/publish'
>>>>>>> 2df90a3ec1774be510d1f7b17771aea3c5dc8f27
        zipAfterPublish: false
    
  # - job: Docker
  #   dependsOn: DotNet
  #   displayName: Build And Push Docker job 
    # steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        containerRegistry: $(containerRegistry)
        repository: $(repository)
        command: 'buildAndPush'
        Dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: $(tag)
